'use strict';
/* Schritt 5: FUNDAMENTALTAFEL.md aus _stand.json, test-fundamental.json und der Ladepruefung - keine Zahl von Hand. */
var fs = require('fs');
var path = require('path');
var Z = require('./zuordnung.js');
var S = JSON.parse(fs.readFileSync(path.join(__dirname, '_stand.json'), 'utf8'));
var T = JSON.parse(fs.readFileSync(path.join(__dirname, 'test-fundamental.json'), 'utf8'));
var LP = JSON.parse(fs.readFileSync('E:/Markt-Dashboard-Archiv/edgar-fsds/_laden-pruefung.json', 'utf8'));
var P = T.pruefungen;
function n(x) { return x === null || x === undefined ? '–' : Number(x).toLocaleString('de-DE'); }
function pz(x) { return x === null || x === undefined ? '–' : String(x).replace('.', ',') + ' %'; }
function f(x, d) { return x === null || x === undefined ? '–' : Number(x).toFixed(d === undefined ? 3 : d).replace('.', ','); }
function pp(x) { return x === null || x === undefined ? '–' : (100 * x).toFixed(2).replace('.', ',') + ' Pp'; }
var Q = S.quartale, o = [];
function z(s) { o.push(s === undefined ? '' : s); }

var neuGesamt = S.fakten.neudarstellungen, wiederholt = S.fakten.wiederholtGleich, eingefuegt = S.fakten.eingefuegt;
var p2 = P['P2 Reproduktion Machbarkeit'], p3 = P['P3 Abstand filed-period und Rundung'], p4 = P['P4 Handrechnung Fundamental-Momentum'], p5 = P['P5 Verteilung Fundamental-Momentum'], p6 = P['P6 Determinismus'], p7 = P['P7 Handproben SEC-API'], p1b = P['P1b 1000 Zufallszugriffe'], p1a = P['P1a Sperrklinke konstruiert'];
var jahre = Object.keys(S.deckung).sort();
var g2019 = S.deckung['2019'].gesamt, g2024 = S.deckung['2024'].gesamt;

z('# Fundamentaltafel 2016–2026 aus den SEC Financial Statement Data Sets — punkt-in-zeit (16.09.2026)');
z();
z('**Auftrag:** `uebergabe/auftrag-fundamentaltafel-2026-09-16.md`. **Gemessen wurde nichts** — das ist die Tafel, die der');
z('Querschnitts-Prüfstand für „gedrückt, aber liefert" lesen wird. Alle Zahlen dieses Berichts erzeugt `bericht-tafel.js`');
z('aus `_stand.json` (Bau) und `test-fundamental.json` (Prüfungen); nichts ist abgetippt. Kennung `' + S.kennung + '`.');
z();
z('## In einem Absatz');
z();
z('**' + n(S.zeilen.gesamt) + ' Zeilen** (je eine je 10-K/10-Q der Panel-CIKs, ' + Q[0] + '–' + Q[Q.length - 1] + ', davon ' + Q.length + ' FSDS-Quartale, die ersten acht als Vorlauf) für');
z('**' + n(S.panel.ciks) + ' CIKs** des 7.299-Reihen-Panels (' + n(S.panel.ohneCik) + ' Reihen ohne CIK), aus ' + n(eingefuegt) + ' Erst-Fakten. Regel „erste Veröffentlichung gilt":');
z(n(neuGesamt) + ' spätere Wiederholungen mit anderem Wert wurden **nicht übernommen** (' + f(100 * neuGesamt / (neuGesamt + wiederholt), 1) + ' % aller Wiederholungen),');
z('die 20 Handproben gegen die SEC-API bestätigen an neudargestellten Fällen: die Tafel trägt den ersten Wert mit dem ersten');
z('Einreichungsdatum, `companyfacts`/`frames` tragen in ' + p7.frameTraegtNichtDenErsten + ' von ' + p7.geprueft + ' Fällen den späteren. Fundamental-Momentum liegt in');
z(pz(Math.round(1000 * S.abgeleitet.fm / S.zeilen.gesamt) / 10) + ' der Zeilen vor; je Kalenderjahr haben ' + pz(g2019.prozent.fm) + ' (2019) bzw. ' + pz(g2024.prozent.fm) + ' (2024) der aktiven Panelreihen');
z('mindestens ein Filing mit FM, in der Klasse ab1000 ' + pz(S.deckung['2019'].ab1000.prozent.fm) + ' bzw. ' + pz(S.deckung['2024'].ab1000.prozent.fm) + '. Leser `fundamental-lesen.js` mit');
z('Sperrklinke: ' + p1b.geliefert + ' von ' + p1b.zugriffe + ' Zufallszugriffen geliefert, ' + p1b.protokollVerstoesse + ' Verstöße. Zweitbau bitgleich (' + p6.gleich + '/' + p6.tafelDateien + ' Dateien). Alle ' + Object.keys(P).length + ' Prüfungen bestanden' + (T.fehler ? ' — NEIN: ' + T.fehler + ' Fehler' : '') + '.');
z();
z('## 1. Bau');
z();
z('**Quelle.** `https://www.sec.gov/files/dera/data/financial-statement-data-sets/<jjjjqn>.zip`, ' + Q.length + ' Quartale ' + Q[0] + '–' + Q[Q.length - 1] + ' (2026q3 noch 404: die SEC stellt das');
z('Paket erst nach Quartalsende bereit). Roh unter `E:/Markt-Dashboard-Archiv/edgar-fsds/<q>.zip` (Beleg) und `<q>/sub.txt`, `<q>/num.txt`;');
z('tag.txt/pre.txt wurden für die neuen Quartale gar nicht erst entpackt. `laden.js` prüft jede Datei beim Laden (ZIP-Größe = Content-Length des');
z('Servers, sub/num-Größe = Eintrag im ZIP-Verzeichnis, erst `.teil`, dann umbenannt); die Nachprüfung `laden-pruefen.js` wiederholt das für die');
z(Object.keys(LP.quartale).length + ' Quartale ' + Object.keys(LP.quartale).sort()[0] + '–' + Object.keys(LP.quartale).sort().pop() + ': ' + LP.fehler + ' Fehler, ' + LP.teilReste.length + ' `.teil`-Reste (die geplante Aufgabe lief zweimal an; drei Kollisionen beim Umbenennen');
z('standen im Log, alle Dateien sind intakt). Die acht Vorlauf-Quartale 2014q1–2015q4 wurden danach mit demselben `laden.js` geladen (Log: 0 Fehler).');
z();
z('**Vorlauf 2014–2015.** Der Auftrag nennt 2016q1 als Start. Ein Handelstag im Januar 2016 braucht aber das 10-K vom Herbst 2015,');
z('und das Fundamental-Momentum braucht acht Quartale Geschichte; ohne Vorlauf hatte 2016 im ersten Bau FM in 52 % der Zeilen gegen');
z('72–78 % ab 2017. Deshalb sind 2014q1–2015q4 als Vorlauf geladen; ihre Filings stehen in `tafel-2014/2015.jsonl` und werden vom');
z('Leser für frühe 2016er-Tage geliefert.');
z();
z('**Schritte** (alle im Studienordner, alle deterministisch): `laden.js` → `auszug.js` (je Quartal die periodischen Berichte aller');
z('Registranten aus sub.txt und die Zeilen der Zieltags ohne Segmente aus num.txt → `edgar-fsds/auszug/<q>-sub.tsv`, `<q>-num.tsv`)');
z('→ `klassen.js` (Umsatzklasse je Reihe und Kalenderjahr) → `bauen.js` (Tafel) → `stand.js` (`_stand.json`) → `test-fundamental.js` → `bericht-tafel.js`.');
z('Bau in ' + S.bauSekunden + ' s.');
z();
z('**Filings.** Periodische Berichte aller Registranten in den Auszügen: ' + n(S.filings.alleRegistranten) + ' (US-Standard ' + n(S.filings.usStandardAlle) + ', 20-F/40-F ' + n(S.filings.auslaendAlle) + ').');
z('Panel-CIKs: **' + n(S.filings.panelUsStandard) + ' 10-K/10-Q-Familie aufgenommen** (' + Object.keys(S.zeilenJeForm).sort().map(function (k) { return k + ' ' + n(S.zeilenJeForm[k]); }).join(', ') + '),');
z('**' + n(S.filings.panelAuslaend) + ' 20-F/40-F nur gezählt** (`fundamentaltafel/_auslaend.json`). Verworfen: ' + S.filings.filedVorPeriod + ' mit filed < period (Plausibilitätsfilter),');
z(S.filings.periodUngueltig + ' ohne gültiges Datum, ' + S.filings.doppelteAdsh + ' doppelte Akzessionen. Rangordnung = (filed, accepted, adsh) über alle Quartale; Quartalsgrenzen in');
z('filed-Ordnung verletzt: ' + S.quartalsgrenzen.verletzt + ', Rangumkehr beim Einfügen: ' + S.fakten.rangUmkehr + ' (beides muss 0 sein, sonst wäre „erste Veröffentlichung" nicht die erste).');
z();
z('**Fakten** (Konzernwert: segments leer, coreg leer): ' + n(S.fakten.zeilen) + ' Auszugszeilen der Panel-Filings → ' + n(eingefuegt) + ' Erst-Fakten (cik, Tag, ddate, qtrs),');
z(n(wiederholt) + ' spätere Wiederholungen mit gleichem Wert, **' + n(neuGesamt) + ' Neudarstellungen** (anderer Wert, nicht übernommen). Verworfen: ' + n(S.fakten.uomFalsch) + ' Fremdwährung/falsche Einheit,');
z(n(S.fakten.zinsNichtFinanz) + ' Zins-Tags bei Nicht-Finanz-SIC, ' + n(S.fakten.qtrsUngueltig) + ' qtrs > 4 oder Datum ungültig, ' + n(S.fakten.wertUngueltig) + ' nicht numerisch. Doppelte Schlüssel mit');
z('verschiedenem Wert INNERHALB eines Filings: ' + S.fakten.doppelImFiling + '.');
z();
z('**Zuordnungstabelle** (`zuordnung.js`; Reihenfolge = Priorität; Verwendung = Rohwert zum Stichtag über alle Zeilen):');
z();
z('| Größe | Tags in Priorität (Verwendung) | Regel |');
z('| --- | --- | --- |');
Object.keys(Z.GRUPPEN).forEach(function (g) {
  var G = Z.GRUPPEN[g], quelle = g === 'aktien' ? S.roh.aktienJeTag : S.roh.tags;
  var liste = G.tags.map(function (t) { return t + ' (' + n(quelle[t] || 0) + ')'; }).join(', ');
  var regel = g === 'umsatz' ? 'Fluss zum Stichtag, qtrs 4 (10-K) bzw. 1 (10-Q); Interest-Tags nur SIC 6000–6799' : g === 'aktien' ? 'dei-Deckblatt im Fenster [period, filed]; Bilanzbestand genau period; gewichtete Zahlen als Fluss zum Stichtag; Issued als letzter Ausweg' : G.art === 'bestand' ? 'Bestand qtrs 0 zum Stichtag' : 'Fluss zum Stichtag, qtrs 4 (10-K) bzw. 1 (10-Q)';
  z('| ' + g + ' | ' + liste + ' | ' + regel + ' |');
});
z();
z('Fallbacks: Nettoergebnis nicht `NetIncomeLoss` in ' + n(S.roh.nettoFallback) + ' Zeilen, Eigenkapital nicht `StockholdersEquity` in ' + n(S.roh.eigenkapitalFallback) + ', Aktienzahl je Tag siehe Tabelle');
z('(die Deckblatt-Zahl `dei:EntityCommonStockSharesOutstanding` steht in ' + n(S.roh.aktienJeTag.EntityCommonStockSharesOutstanding || 0) + ' Zeilen — sie fehlt in num.txt, wie in der Machbarkeit gesehen).');
z();
z('**Quartalsfluss je Stichtag und 4-Quartals-Summen.** Für jedes Filing werden acht Stichtage D0 = period, D1 … D7 (je drei Monate');
z('zurück, Monatsende) gebildet und je Größe der Quartalswert mit nur zu diesem Rang bekannten Fakten bestimmt: direkt (qtrs 1), sonst');
z('mit demselben Tag Jahr minus drei Vorquartale (Auftrag), Jahr minus 9-Monats-YTD, YTD-Differenzen. Wege über alle Zeilen × 8 Stichtage:');
z();
z('| Größe | direkt | Jahr − 3 Quartale | Jahr − YTD3 | YTD2 − Q1 | YTD3 − YTD2 | YTD3 − 2Q | Lücke je Stichtag D0…D7 |');
z('| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |');
['umsatz', 'netto', 'operativ'].forEach(function (g) { var w = S.wege[g]; z('| ' + g + ' | ' + n(w.direkt) + ' | ' + n(w['jahr-3q']) + ' | ' + n(w['jahr-ytd3']) + ' | ' + n(w.ytd2) + ' | ' + n(w.ytd3) + ' | ' + n(w['ytd3-2q']) + ' | ' + S.luecken[g].jeQuartal.map(n).join(' / ') + ' |'); });
z();
z('4Q-Summe nur, wenn alle vier Stichtage da sind: Lücken Umsatz ' + n(S.luecken.umsatz.summe4q) + ', Netto ' + n(S.luecken.netto.summe4q) + ', operativ ' + n(S.luecken.operativ.summe4q) + ' von ' + n(S.zeilen.gesamt) + ' Zeilen;');
z('Vorjahresfenster (D4…D7): ' + n(S.luecken.umsatz.summe4qVor) + ' / ' + n(S.luecken.netto.summe4qVor) + ' / ' + n(S.luecken.operativ.summe4qVor) + '. Der Weg „Jahr − YTD3" geht über den Auftrag hinaus (dort: „sonst Lücke");');
z('er ist je Quartal mit `y` markiert, damit der Prüfstand ihn ausschließen kann, wenn er die strenge Regel will.');
z();
z('**Abgeleitet je Filing:** roa = netto4Q / Vermögen(D0); roaVor = netto4Q_vor / Vermögen(D4); **fm = roa − roaVor** (Novy-Marx 2015);');
z('umsatzWachstum = umsatz4Q / umsatz4Q_vor − 1. Vorhanden: roa ' + n(S.abgeleitet.roa) + ', fm ' + n(S.abgeleitet.fm) + ', umsatzWachstum ' + n(S.abgeleitet.umsatzWachstum) + ' Zeilen.');
z();
z('**Zuordnung CIK → Kürzel** aus `panel.json` der Machbarkeit: lebende Reihen über die SEC-Tickertabelle (ein lebendes Kürzel zeigt');
z('auf den lebenden Registranten — die Falle betrifft wiederverwendete Kürzel Verschwundener), verschwundene über die zeitgefensterte');
z('Volltext-Zuordnung von `verschwundene-gruende-2026-09-12/edgar/` (Sicherheit stark/mittel/schwach wird in `_reihen.json` mitgeführt;');
z('1.003 schwache Zuordnungen). Mehrere Kürzel je CIK (Umfirmierung) stehen als Liste `sym` in der Zeile.');
z();
z('**Ablage** `fundamentaltafel/` (nicht im Repo, ' + Object.keys(S.hashes).filter(function (k) { return /^tafel-/.test(k); }).length + ' Jahresdateien nach filed-Jahr, ' + n(Math.round(Object.keys(S.hashes).reduce(function (a, k) { return a + S.hashes[k].bytes; }, 0) / 1e6)) + ' MB): `tafel-<jahr>.jsonl`, je Zeile');
z('`{sym, cik, sic, sektor, form, period, filed, accepted, fy, fp, q, adsh, roh{umsatz, netto, operativ, umsatzkosten, fue, vermoegen, eigenkapital, aktien, qtrs},');
z('rohTags, quartale{umsatz, netto, operativ: [D0…D7]}, wege, quartalsTags, summe4q{…, …Vor}, vermoegenVor, abgeleitet{roa, roaVor, fm, umsatzWachstum},');
z('marken{luecken, erstVonFrueher, nettoFallback, eigenkapitalFallback, aktienFallback}}`; dazu `_reihen.json` (Kürzel → CIK), `_auslaend.json`,');
z('`_neudarstellungen.json` (' + n(neuGesamt) + ' Fälle mit erstem und späterem Wert), `_bau.json` (Zähler, SHA-256). Im Repo: Skripte, `_stand.json`, dieser Bericht.');
z();
z('## 2. Deckung je Umsatzklasse × Jahr');
z();
z('Klasse = Median des Dollar-Umsatzes über die Handelstage des Kalenderjahres (≥ 40 Umsatztage, sonst „dünn"), wie Prüfstand §1.5.');
z('Spalten in Prozent der aktiven Reihen der Klasse: Bericht = mindestens ein 10-K/10-Q mit `filed` im Jahr (nur das trägt die Tafel);');
z('20-F/40-F = nur gezählt; Umsatz/Netto/Vermögen/Aktien = Rohwert zum Stichtag in einem Filing des Jahres; 4Q-Netto = vollständige');
z('4-Quartals-Summe; FM = Fundamental-Momentum vorhanden. 2016 ist trotz Vorlauf dünner (Quartalswerte vor 2014 fehlen).');
z();
S.klassen.concat(['gesamt']).forEach(function (k) {
  z('**' + k + '**');
  z();
  z('| Jahr | aktiv | mit CIK | Bericht | 20-F/40-F | Umsatz | Netto | Vermögen | Aktien | 4Q-Netto | FM |');
  z('| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |');
  jahre.forEach(function (j) { var c = S.deckung[j][k], p = c.prozent; z('| ' + j + ' | ' + n(c.aktiv) + ' | ' + pz(p.mitCik) + ' | ' + pz(p.bericht) + ' | ' + pz(p.auslaend) + ' | ' + pz(p.umsatz) + ' | ' + pz(p.netto) + ' | ' + pz(p.vermoegen) + ' | ' + pz(p.aktien) + ' | ' + pz(p.summe4qNetto) + ' | ' + pz(p.fm) + ' |'); });
  z();
});
z('**Reproduktion der Machbarkeit (2019q2, 2024q2, Prüfung P2).** Reihen mit US-Standardbericht je Klasse: gleich bis auf die verworfenen');
z('Filings mit filed < period (' + Object.keys(p2).filter(function (k) { return /q/.test(k); }).map(function (q) { return q + ': ' + p2[q].verworfenFiledVorPeriod.length; }).join(', ') + '). Werte Zeile für Zeile (adsh) gegen `deckung-reihen.json`:');
Object.keys(p2).filter(function (k) { return /q/.test(k); }).forEach(function (q) { var a = p2[q]; z('- ' + q + ': gleich Umsatz ' + n(a.wertGleich.umsatz) + ', Vermögen ' + n(a.wertGleich.vermoegen) + ', Aktien ' + n(a.wertGleich.aktien) + '; durch „erste Veröffentlichung" anders ' + JSON.stringify(a.wertDurchErsteVeroeffentlichung) + '; Regelunterschied Aktienzahl ' + a.regelunterschiedAktien + ' (Machbarkeit nahm die erste Dateizeile der gewichteten Zahl, die Tafel qtrs = Sollquartal); unerklärt anders: ' + a.wertAndersN + '.'); });
z();
z('## 3. Verteilungen');
z();
z('**filed − period je Formulartyp** (Tage; Panel-Filings sind liquider als der FSDS-Durchschnitt der Machbarkeit):');
z();
z('| Form | n | p10 | Median | p90 | Mittel | > 45 Tage | > 90 Tage |');
z('| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |');
Object.keys(p3.abstand).sort().forEach(function (a) { var s = p3.abstand[a]; z('| ' + a + ' | ' + n(s.n) + ' | ' + n(s.p10) + ' | ' + n(s.p50) + ' | ' + n(s.p90) + ' | ' + f(s.mittel, 1) + ' | ' + pz(Math.round(1000 * s.ueber45 / s.n) / 10) + ' | ' + pz(Math.round(1000 * s.ueber90 / s.n) / 10) + ' |'); });
z();
z('(K = 10-K, KA = 10-K/A, KT = 10-KT, Q = 10-Q, QA = 10-Q/A, QT = 10-QT.) **Monatsend-Rundung:** der Instanzname in sub.txt trägt den echten');
z('Stichtag; er weicht von `period` in ' + pz(p3.rundung.gesamt.anteilGerundet) + ' der Filings ab (' + n(p3.rundung.gesamt.gerundet) + ' von ' + n(p3.rundung.gesamt.n) + '; ohne Datum im Namen ' + n(p3.rundung.gesamt.ohneDatumImNamen) + '), je Form: ' + Object.keys(p3.rundung.jeArt).sort().map(function (a) { return a + ' ' + pz(p3.rundung.jeArt[a].anteilGerundet); }).join(', ') + '.');
z('Median der Verschiebung ' + (p3.rundung.jeArt.Q && p3.rundung.jeArt.Q.rundungTage.p50 !== null ? n(p3.rundung.jeArt.Q.rundungTage.p50) + ' Tage (10-Q)' : '–') + ' — für jede Verknüpfung mit Originaldaten ±7 Tage Toleranz.');
z();
z('**Fundamental-Momentum je Jahr** (Zeilen nach filed-Jahr; fm in Prozentpunkten des Vermögens):');
z();
z('| Jahr | Zeilen | mit FM | Lücke FM | FM Median | FM P5 | FM P95 | ROA Median | Umsatzwachstum Median |');
z('| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |');
Object.keys(p5.jeJahr).sort().forEach(function (j) { var e = p5.jeJahr[j]; z('| ' + j + ' | ' + n(e.zeilen) + ' | ' + n(e.mitFm) + ' | ' + pz(e.anteilLueckeFm) + ' | ' + pp(e.fmVerteilung.p50) + ' | ' + pp(e.fmVerteilung.p5) + ' | ' + pp(e.fmVerteilung.p95) + ' | ' + pp(e.roaVerteilung.p50) + ' | ' + pp(e.umsatzWachstumVerteilung.p50) + ' |'); });
z();
z('**Handrechnung (P4)** an drei Firmen über je acht Filings, unabhängig aus den Auszügen nachgerechnet (Quartals-Netto direkt oder Jahr − 3 Quartale, Vermögen zum Stichtag und vier Quartale früher):');
z();
Object.keys(p4).filter(function (k) { return p4[k] && p4[k].filings; }).forEach(function (sym) {
  z('*' + sym + '* (CIK ' + p4[sym].cik + '): ' + p4[sym].filings.filter(function (x) { return x.stimmt; }).length + ' von ' + p4[sym].filings.length + ' stimmen');
  z();
  z('| Form | period | filed | netto4Q | Vermögen | ROA | ROA vor | FM (Hand) | FM (Tafel) | Wege |');
  z('| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |');
  p4[sym].filings.forEach(function (x) { z('| ' + x.form + ' | ' + x.period + ' | ' + x.filed + ' | ' + n(x.netto4Q) + ' | ' + n(x.vermoegen) + ' | ' + pp(x.roa) + ' | ' + pp(x.roaVor) + ' | ' + pp(x.fm) + ' | ' + pp(x.tafelFm) + ' | ' + x.tafelWege + ' |'); });
  z();
});
z('## 4. Neudarstellungen');
z();
z(n(neuGesamt) + ' Schlüssel (cik, Tag, ddate, qtrs) wurden später mit anderem Wert wieder eingereicht — je Größe: ' + Object.keys(S.fakten.neuJeGruppe).sort().map(function (g) { return g + ' ' + n(S.fakten.neuJeGruppe[g]); }).join(', ') + ';');
z('je Form des späteren Filings: ' + Object.keys(S.fakten.neuJeSpaeterForm).sort().map(function (g) { return g + ' ' + n(S.fakten.neuJeSpaeterForm[g]); }).join(', ') + '. Die meisten sind Vergleichszahlen im nächsten 10-Q/10-K (aufgegebene');
z('Geschäftsbereiche, Umgliederungen, Abspaltungen), nicht /A-Korrekturen. **Die Tafel trägt in allen Fällen den ersten Wert.**');
z();
z('**20 Handproben gegen die SEC-API (P7, `companyconcept`, ' + p7.anfragen + ' Anfragen, Cache `edgar-fsds/api-cache/`):** ' + p7.bestanden + ' von ' + p7.geprueft + ' bestanden — Tafelwert = erster Wert mit erstem `filed`,');
z('die API führt beide Einreichungen mit denselben Werten und Daten. Der Eintrag mit `frame` (das, was `companyfacts`/`frames` als Wert der Periode liefern)');
z('trägt in ' + p7.frameTraegtNichtDenErsten + ' Fällen NICHT die Erstveröffentlichung (in ' + p7.frameGleichSpaeterem + ' genau den späteren Wert). Kandidaten: ' + n(p7.kandidaten) + ' Fälle mit ≥ 1 % Abweichung, gewählt eine je Firma, liquide Klassen zuerst, über die Jahre verteilt.');
z();
z('| Reihe | Klasse | Tag | Stichtag | qtrs | Tafel (erster Wert, filed) | später (Wert, filed) | API frame-Wert | ok |');
z('| --- | --- | --- | --- | ---: | --- | --- | --- | --- |');
p7.faelle.forEach(function (c) { z('| ' + c.reihe + ' | ' + (c.klasse || '–') + ' | ' + c.tag + ' | ' + c.ddate + ' | ' + c.qtrs + ' | ' + n(c.tafel.wert) + ' (' + c.tafel.filed + ', ' + c.tafel.form + ') | ' + n(c.spaeter.wert) + ' (' + c.spaeter.filed + ', ' + c.spaeter.form + ') | ' + (c.api.frame ? n(c.api.frame.val) + ' ' + c.api.frame.frame : '–') + ' | ' + (c.ok ? 'ja' : 'NEIN') + ' |'); });
z();
z('## 5. Prüfungen (`test-fundamental.js`, ' + T.sekunden + ' s)');
z();
Object.keys(P).forEach(function (k) { z('- ' + (P[k].ok ? 'bestanden' : '**FEHLER**') + ' — ' + k + (P[k].kurz ? ': ' + P[k].kurz : '') + (P[k].uebersprungen ? ' (übersprungen)' : '')); });
z();
z('Leck-Probe im Einzelnen: konstruiertes Filing mit filed = tag wirft (' + p1a.geworfenBeiFiledGleichTag + '), filed = tag − 1 liefert (' + p1a.geliefertBeiFiledVortag + '); die Suche liefert am Einreichungstag');
z('das Vorgänger-Filing (' + p1a.sucheAmTag + ') und am Folgetag das neue (' + p1a.sucheDanach + '). ' + p1b.zugriffe + ' Zufallszugriffe (Kürzel × Handelstag 2016–2026, Saat 20260916): ' + p1b.geliefert + ' geliefert,');
z(p1b.zaehler.null_ohneFiling + ' ohne Filing vor dem Tag, ' + p1b.zaehler.null_veraltet + ' veraltet (Aktualitäts-Tor 456 Tage), ' + p1b.zaehler.null_ohneReihe + ' ohne CIK; Protokoll ' + p1b.protokollEintraege + ' Einträge, ' + p1b.protokollVerstoesse + ' mit filed ≥ tag.');
z('Determinismus: Zweitbau in einen anderen Ordner (' + p6.zweitbauSekunden + ' s) — ' + p6.gleich + ' von ' + p6.tafelDateien + ' Dateien SHA-256-gleich; Zweitauszug 2019q2/2024q2 aus den Roh-Quartalen ' + p6.auszugGleich + '/4 gleich.');
z();
z('## 6. Sektorschlüssel');
z();
z('GICS haben wir nicht; `sic` aus sub.txt (je Filing, kann sich ändern) wird nach den zehn SIC-Divisionen gruppiert (`zuordnung.js sektorVonSic`):');
z();
z('| Division | SIC | Zeilen | CIKs |');
z('| --- | --- | ---: | ---: |');
Z.SIC_DIVISIONEN.forEach(function (d) { var s = S.sektoren.filter(function (x) { return x.sektor === d.name; })[0]; z('| ' + d.name + ' | ' + d.von + '–' + d.bis + ' | ' + n(s ? s.zeilen : 0) + ' | ' + n(s ? s.ciks : 0) + ' |'); });
S.sektoren.filter(function (x) { return !Z.SIC_DIVISIONEN.some(function (d) { return d.name === x.sektor; }); }).forEach(function (s) { z('| ' + s.sektor + ' | – | ' + n(s.zeilen) + ' | ' + n(s.ciks) + ' |'); });
z();
z('Für den Prüfstand ist das grob (Verarbeitendes Gewerbe ist eine Division); feinere Schnitte sind über die zweistellige SIC (Major Group, `sic` steht in jeder Zeile) möglich.');
z();
z('## 7. Was diese Tafel nicht weiß');
z();
z('- **Vorab-Meldungen per 8-K.** Die Quartalszahl ist meist **Wochen vor** dem 10-Q per Pressemeldung (8-K Item 2.02) bekannt — 10-Q Median ' + n(p3.abstand.Q.p50) + ' Tage nach Stichtag, die Pressemeldung oft 1–3 Wochen früher. Die Tafel nimmt bewusst das spätere `filed` des 10-Q: konservativ (nie zu früh), aber ein Ranking, das am 10-Q-Tag reagiert, kommt später als der Markt. Wer das braucht, muss die 8-K-Daten aus dem Volltextindex dazuladen — die Tafel hat sie nicht.');
z('- **20-F/40-F** (ausländische Emittenten, ADR, kanadische CS): ' + n(S.filings.panelAuslaend) + ' Panel-Filings nur gezählt (`_auslaend.json`), nicht aufgenommen — IFRS-Tags, Fremdwährung, jährlich. Die liquiden Klassen verlieren dadurch je Jahr die Reihen in Spalte 20-F/40-F der Deckungstafel.');
z('- **Dividenden, Aktienrückkäufe, Cashflow** stehen nicht in der Tafel (Tags nicht aufgenommen); Kapitalmaßnahmen, Ausschüttungsrendite und B/M-Nenner brauchen andere Quellen (Aktienzahl ist die Bilanzzahl, Mehrklassen-Emittenten melden je Klasse in Segmenten).');
z('- **Fremdwährungs-Filer** in 10-K/10-Q (uom ≠ USD): ' + n(S.fakten.uomFalsch) + ' Zeilen verworfen, keine Umrechnung.');
z('- **CIK-Zuordnung** verschwundener Reihen: 1.003 „schwach", CIK-Wechsel bei Umstrukturierungen (APA, ABC → COR) — die Sicherheit steht in `_reihen.json`, der Prüfstand kann schwache Zuordnungen ausschließen.');
z('- **Umsatz-Tag-Wildwuchs:** firmeneigene Umsatz-Tags (≈ 3 % der Filings, Machbarkeit) sind verloren; Umsatzkosten nur zu ' + pz(Math.round(1000 * S.roh.umsatzkosten / S.zeilen.gesamt) / 10) + ' der Zeilen (Bruttoprofitabilität bleibt lückig).');
z('- **Verzug der Quelle:** die SEC stellt ein FSDS-Quartal ≈ 2 Wochen nach Quartalsende bereit; 2026q3 fehlt (404). Filings seit 01.07.2026 sind nicht in der Tafel — für den laufenden Rand braucht es den täglichen EDGAR-Index. Der Prüfstand darf die Tafel nur bis 30.06.2026 als vollständig ansehen.');
z('- **Uhrzeit:** `accepted` steht in der Zeile; nutzbar ist ein Filing ab dem Handelstag NACH `filed` (der Leser liefert nur filed < tag). Filings nach 17:30 ET tragen ohnehin den Folgetag.');
z('- **Der Weg „Jahr − YTD3"** und die YTD-Differenzen gehen über die Auftragsregel hinaus (Markierung `y`, `2`, `3`, `4` in `wege`), Anteil siehe §1.');
z('- **Neudarstellungen sind nicht in den Zeilen** markiert (das wäre ein Blick in die Zukunft); sie stehen nur in `_neudarstellungen.json` für Diagnosen.');
z();
z('## 8. Anschluss');
z();
z('Leser: `var F = require(\'studien/fundamental-machbarkeit-2026-09-16/fundamental-lesen.js\'); var t = F.oeffne(); t.fundamentalAm(\'AAPL\', \'2024-05-06\')` → Zeile oder null;');
z('`t.protokoll()` für die Sperrklinke, `t.zaehler` (geliefert / ohne Filing / veraltet / ohne Reihe), Option `{maxAlterTage: null}` schaltet das Aktualitäts-Tor ab.');
z('Nächster Auftrag (Prüfstand): Rangfunktion „gedrückt, aber liefert" über `abgeleitet.fm` und die Kursdrift, Vorregistrierung mit Klassen, Aktualitäts-Tor und Umgang mit `y`-Wegen.');
z();
fs.writeFileSync(path.join(__dirname, 'FUNDAMENTALTAFEL.md'), o.join('\n') + '\n');
console.log('FUNDAMENTALTAFEL.md geschrieben, ' + o.length + ' Zeilen');
